export { default as useFeature } from './useFeature'
export { default as useFetch } from './useFetch'
export { default as useTrends } from './useTrends'
export { default as useMoviesTrends } from './useMoviesTrends'
export { default as useShows } from './useShows'
export { default as usePersons } from './usePersons'
export { default as useNowPlayingMovies } from './useNowPlayingMovies'
export { default as useUpcomingMovies } from './useUpcomingMovies'