export { default as SkeletonButton } from './Button'
export { default as SkeletonHeader } from './Header'
export { default as SkeletonParagraph } from './Paragraph'
export { default as SkeletonText1 } from './Text1'
export { default as SkeletonText2 } from './Text2'