name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          cmd: test